#!/usr/bin/env perl                                                                                                                                                                                                               
                                                                                                                                                                                                                                  
use strict;                                                                                                                                                                                                                       
use warnings;                                                                                                                                                                                                                     
use Test::More;                                                                                                                                                                                                                   
use DDG::Test::Goodie;                                                                                                                                                                                                            
                                                                                                                                                                                                                                  
zci answer_type => 'chucknorris';                                                                                                                                                                                                     
zci is_cached   => 0;                                                                                                                                                                                                             
                                                                                                                                                                                                                                  
my @facts = (                                                                                                                                                                                                                   
    '-ANY-',                                                                                                                                                                                                                      
    structured_answer => {                                                                                                                                                                                                        
        input     => [],                                                                                                                                                                                                          
        operation => 'Random Chuck Norris fact',                                                                                                                                                                                            
        result    => '-ANY-'                                                                                                                                                                                                      
    });                                                                                                                                                                                                                           
                                                                                                                                                                                                                                  
ddg_goodie_test(                                                                                                                                                                                                                  
    [qw( DDG::Goodie::ChuckNorris )],                                                                                                                                                                                                 
    'chuck norris fact'           => test_zci(@facts),                                                                                                                                                                    
);                                                                                                                                                                                                                                
                                                                                                                                                                                                                                  
done_testing; 