#!/usr/bin/env perl

use strict;
use warnings;

use Test::More;
use DDG::Test::Goodie;

zci answer_type => 'conversions';
zci is_cached   => 1;

ddg_goodie_test(
    ['DDG::Goodie::Conversions'],
    # Example queries
    'convert 5 oz to grams'    => test_zci('5 ounces = 141.747 grams',              html => '-ANY-'),
    '5 ounces to g'            => test_zci('5 ounces = 141.747 grams',              html => '-ANY-'),
    '0.5 nautical miles in km' => test_zci('0.5 nautical miles = 0.926 kilometers', html => '-ANY-'),
    # Explicit conversion requests
    'convert 1 ton to long ton'      => test_zci('1 ton = 0.893 long tons',                    html => '-ANY-'),
    'convert 158 ounce to lbm'       => test_zci('158 ounces = 9.875 pounds',                  html => '-ANY-'),
    'convert 0.111 stone to pound'   => test_zci('0.111 stone = 1.554 pounds',                 html => '-ANY-'),
    'convert 5 feet to in'           => test_zci('5 feet = 60 inches',                         html => '-ANY-'),
    'convert 5 kelvin to fahrenheit' => test_zci('5 kelvin = -450.670 degrees fahrenheit',     html => '-ANY-'),
    'convert 25 inches into feet'    => test_zci('25 inches = 2.083 feet',                     html => '-ANY-'),
    'convert 5 f to celsius'         => test_zci('5 degrees fahrenheit = -15 degrees celsius', html => '-ANY-'),
    'convert km to cm'               => test_zci('1 kilometer = 100,000 centimeters',          html => '-ANY-'),
    'convert 10ms to seconds'        => test_zci('10 milliseconds = 0.010 seconds',            html => '-ANY-'),
    'convert 1 yb to yib'            => test_zci('1 yottabyte = 0.827 yobibytes',              html => '-ANY-'),
    'convert 1stone to lbs'          => test_zci('1 stone = 14 pounds',                        html => '-ANY-'),
    'convert 5 bytes to bit'         => test_zci('5 bytes = 40 bits',                          html => '-ANY-'),
    # Implicit conversion requests
    '3 kilogramme to pound'            => test_zci('3 kilograms = 6.614 pounds',                       html => '-ANY-'),
    '1.3 tonnes to ton'                => test_zci('1.3 metric tons = 1.433 tons',                     html => '-ANY-'),
    '2 tons to kg'                     => test_zci('2 tons = 1,814.372 kilograms',                     html => '-ANY-'),
    '1 ton to kilos'                   => test_zci('1 ton = 907.186 kilograms',                        html => '-ANY-'),
    '3.9 oz in g'                      => test_zci('3.9 ounces = 110.563 grams',                       html => '-ANY-'),
    '2 miles to km'                    => test_zci('2 miles = 3.219 kilometers',                       html => '-ANY-'),
    '0.5 nautical mile to klick'       => test_zci('0.5 nautical miles = 0.926 kilometers',            html => '-ANY-'),
    '500 miles in metres'              => test_zci('500 miles = 804,672.249 meters',                   html => '-ANY-'),
    '25 cm in inches'                  => test_zci('25 centimeters = 9.843 inches',                    html => '-ANY-'),
    '1760 yards to miles'              => test_zci('1,760 yards = 1 mile',                             html => '-ANY-'),
    '3520yards to miles'               => test_zci('3,520 yards = 2 miles',                            html => '-ANY-'),
    '30cm in in'                       => test_zci('30 centimeters = 11.811 inches',                   html => '-ANY-'),
    '36 months to years'               => test_zci('36 months = 3 years',                              html => '-ANY-'),
    '43200 seconds in hours'           => test_zci('43,200 seconds = 12 hours',                        html => '-ANY-'),
    '4 hours to minutes'               => test_zci('4 hours = 240 minutes',                            html => '-ANY-'),
    '1 bar to pascal'                  => test_zci('1 bar = 100,000 pascals',                          html => '-ANY-'),
    '1 kilopascal to psi'              => test_zci('1 kilopascal = 0.145 pounds per square inch',      html => '-ANY-'),
    '1 atm to kpa'                     => test_zci('1 atmosphere = 101.325 kilopascals',               html => '-ANY-'),
    '5yrds to km'                      => test_zci('5 yards = 0.005 kilometers',                       html => '-ANY-'),
    '12" to cm'                        => test_zci('12 inches = 30.480 centimeters',                   html => '-ANY-'),
    '42 kilowatt hours in joules'      => test_zci('42 kilowatt-hours = 1.51 * 10^8 joules',           html => '-ANY-'),
    '2500kcal in tons of tnt'          => test_zci('2,500 large calories = 0.003 tons of TNT',         html => '-ANY-'),
    '90 ps in watts'                   => test_zci('90 metric horsepower = 66,194.888 watts',          html => '-ANY-'),
    '1 gigawatt in horsepower'         => test_zci('1 gigawatt = 1.34 * 10^6 horsepower',              html => '-ANY-'),
    '180 degrees in radians'           => test_zci('180 degrees = 3.142 radians',                      html => '-ANY-'),
    '270 degrees in quadrants'         => test_zci('270 degrees = 3 quadrants',                        html => '-ANY-'),
    '180 degrees in grads'             => test_zci('180 degrees = 200 gradians',                       html => '-ANY-'),
    '45 newtons to pounds force'       => test_zci('45 newtons = 10.116 pounds force',                 html => '-ANY-'),
    '8 poundal to newtons'             => test_zci('8 poundals = 1.106 newtons',                       html => '-ANY-'),
    '10 mg to tons'                    => test_zci('10 milligrams = 1.1 * 10^-8 tons',                 html => '-ANY-'),
    '10000 minutes in microseconds'    => test_zci('10,000 minutes = 6 * 10^11 microseconds',          html => '-ANY-'),
    '5 GB to megabyte'                 => test_zci('5 gigabytes = 5,000 megabytes',                    html => '-ANY-'),
    '0.013 mb in bits'                 => test_zci('0.013 megabytes = 104,000 bits',                   html => '-ANY-'),
    '0,013 mb in bits'                 => test_zci('0,013 megabytes = 104.000 bits',                   html => '-ANY-'),
    '1 exabyte to pib'                 => test_zci('1 exabyte = 888.178 pebibytes',                    html => '-ANY-'),
    '16 years in months'               => test_zci('16 years = 192 months',                            html => '-ANY-'),
    '1 year in months'                 => test_zci('1 year = 12 months',                               html => '-ANY-'),
    '360 degrees in revolutions'       => test_zci('360 degrees = 1 revolution',                       html => '-ANY-'),
    '12 degrees Celsius to Fahrenheit' => test_zci('12 degrees celsius = 53.600 degrees fahrenheit',   html => '-ANY-'),
    '1 degrees Fahrenheit to celsius'  => test_zci('1 degrees fahrenheit = -17.222 degrees celsius',   html => '-ANY-'),
    '0 c in k'                         => test_zci('0 degrees celsius = 273.150 kelvin',               html => '-ANY-'),
    '234 f to c'                       => test_zci('234 degrees fahrenheit = 112.222 degrees celsius', html => '-ANY-'),
    '234 f to k'                       => test_zci('234 degrees fahrenheit = 385.372 kelvin',          html => '-ANY-'),
    'metres from 20 yards'             => test_zci('20 yards = 18.288 meters',                         html => '-ANY-'),
    '7 milligrams to micrograms'       => test_zci('7 milligrams = 7,000 micrograms',                  html => '-ANY-'),
    'inches in 5 meters'               => test_zci('5 meters = 196.851 inches',                        html => '-ANY-'),
    '5 inches in meters'               => test_zci('5 inches = 0.127 meters',                          html => '-ANY-'),
    'millilitres in a gallon'          => test_zci('1 us gallon = 3,785.412 millilitres',              html => '-ANY-'),
    'gallons in a millilitres'         => test_zci('1 millilitre = 0.000264 us gallons',               html => '-ANY-'),
    'feet in an inches'                => test_zci('1 inch = 0.083 feet',                              html => '-ANY-'),
    'ml in gallons'                    => test_zci('1 millilitre = 0.000264 us gallons',               html => '-ANY-'),
    'ml in gallon'                     => test_zci('1 us gallon = 3,785.412 millilitres',              html => '-ANY-'),
    'mm in inches'                     => test_zci('1 millimeter = 0.039 inches',                      html => '-ANY-'),
    'mm in inch'                       => test_zci('1 inch = 25.400 millimeters',                      html => '-ANY-'),
    # Unusual number formats
    '3e60 degrees in revolutions'   => test_zci('3 * 10^60 degrees = 8.33 * 10^57 revolutions', html => '-ANY-'),
    '4,1E5 newtons to pounds force' => test_zci('4,1 * 10^5 newtons = 92.171,667 pounds force', html => '-ANY-'),
    '4E5 newtons to pounds force'   => test_zci('4 * 10^5 newtons = 89,923.577 pounds force',   html => '-ANY-'),
    '5,0 GB to megabyte'            => test_zci('5,0 gigabytes = 5.000 megabytes',              html => '-ANY-'),
    '3.5e-2 miles to inches'        => test_zci('3.5 * 10^-2 miles = 2,217.602 inches',         html => '-ANY-'),
    # Areas and volumes
    '100 square metres in hectares'    => test_zci('100 square meters = 0.010 hectares', html => '-ANY-'),
    '0.0001 hectares in square metres' => test_zci('0.0001 hectares = 1 square meter', html => '-ANY-'),
    '1 imperial gallon in litres'      => test_zci('1 imperial gallon = 4.546 litres',   html => '-ANY-'),
    '0.001 litres in millilitres'      => test_zci('0.001 litres = 1 millilitre', html => '-ANY-'),
    '1 hectare in square metres'       => test_zci('1 hectare = 10,000 square meters',   html => '-ANY-'),
    # Question-style
    'what is 1 inch in cm'              => test_zci('1 inch = 2.540 centimeters',           html => '-ANY-'),
    'what are 10 yards in metres'       => test_zci('10 yards = 9.144 meters',              html => '-ANY-'),
    'how long is 42 days in mins'       => test_zci('42 days = 60,480 minutes',             html => '-ANY-'),
    'how much is 40 kelvin in celsius'  => test_zci('40 kelvin = -233.150 degrees celsius', html => '-ANY-'),
    'how much is 40 kelvin in celsius?' => test_zci('40 kelvin = -233.150 degrees celsius', html => '-ANY-'),
    'how many metres in 10 of yard?'    => test_zci('10 yards = 9.144 meters',              html => '-ANY-'),
    'how many metres in 10 yards?'      => test_zci('10 yards = 9.144 meters',              html => '-ANY-'),
    'how many pounds in 1 kilogram'     => test_zci('1 kilogram = 2.205 pounds',            html => '-ANY-'),
    'how many pounds in kilogram'       => test_zci('1 kilogram = 2.205 pounds',            html => '-ANY-'),
    'how many pounds in kilograms?'     => test_zci('1 pound = 0.454 kilograms',            html => '-ANY-'),
    'how many cm in a metre?'           => test_zci('1 meter = 100 centimeters',            html => '-ANY-'),
    'how many cm in metres?'            => test_zci('1 centimeter = 0.010 meters',          html => '-ANY-'),
    'how many cm in an inch?'           => test_zci('1 inch = 2.540 centimeters',           html => '-ANY-'),
    'how much is a liter in gallons?'   => test_zci('1 litre = 0.264 us gallons',           html => '-ANY-'),
    'how much is a gallon in litres?'   => test_zci('1 us gallon = 3.785 litres',           html => '-ANY-'),
    'how many gallons in a litre'       => test_zci('1 litre = 0.264 us gallons',           html => '-ANY-'),
    'number of cm in 100 m'             => test_zci('100 meters = 10,000 centimeters',      html => '-ANY-'),
    # Intentionally untriggered
    '5 inches in 5 meters'            => undef,
    'convert 1 cm to 2 mm'            => undef,
    'inching towards the goal'        => undef,
    '6^2 oz to grams'                 => undef,
    'NaN oz to stones'                => undef,
    '45x10 oz to stones'              => undef,
    'convert -9 g to ozs'             => undef,
    'convert 5 oz to yards'           => undef,
    'puff toke to kludge'             => undef,
    'Inf oz to stones'                => undef,
    'convert -5 kelvin to fahrenheit' => undef,
    'use a ton of stones'             => undef,
    'shoot onself in the foot'        => undef,
    'foot in both camps'              => undef,
);

done_testing;
